### ISSUE TITLE
5 DACS demo images registered on IPDB

### ISSUE THREAD

**Issue by wrigley** [bigchaindb/org#13]
# Abstract
If I go to whereonthe.net, and I search for an image that is in the DACS DB, then the results page should include a card that has metadata {title, artist, year, ascribe ID}, link to DACS, and link to ascribe.

# Motivation
For creators: a new means to get proper attribution, and license their work. For web surfers: a means to see who has rights to an image. For us: high value prop for DACS because of attribution & licensing.

# Goals

### Upload DACS data to IPDB
* [x] Define implementation roadmap (https://github.com/ascribe/specs/issues/29)
* [x] Build scaffolding for each project: COALA service, COALA models, COALA BDB plugin, BDB driver(https://github.com/ascribe/specs/issues/36)
* [x] Decide on notion of ownership for Creations (https://github.com/bigchaindb/pycoalaip/issues/6)
* [x] Define REST API contracts ([milestone](https://github.com/bigchaindb/bigchaindb/milestone/1))
* [x] Define pycoalaip API contract (https://github.com/bigchaindb/pycoalaip/issues/3)
* [x] Define pycoalaip-bigchaindb API contract (https://github.com/bigchaindb/pycoalaip-bigchaindb/issues/2)
* [x] Implement the **registration** of a `Creation` ([project](https://github.com/bigchaindb/org/issues/19))
* [x] Images get registered from us on IPDB using pycoalaip (https://github.com/ascribe/memetracker/issues/17)

**Removed out of scope**:
* [x] ~~Create backend boilerplate (https://github.com/ascribe/specs/issues/30)~~
* [x] ~~Investigate interoperability between Django and pycoalaip~~
* [x] ~~Support IPLD in BDB (https://github.com/bigchaindb/bigchaindb/issues/485)~~
* [x] ~~Branch out and implement other use-cases~~

### Build WOTN cards to support use case
* [x] Scrape DACS data
* [x] Add data to WOTN and image-match
* [x] Build WOTN card
* [x] Push to production
* [x] Add the registration transaction's id as meta data to the image (https://github.com/ascribe/memetracker/issues/16)
* [x] Show transaction id in UI (https://github.com/ascribe/memetracker/issues/11)

# Targets:
* Finish scaffolding by **Tuesday, Aug. 9th**
* Support DACS cards in WOTN by **Monday, Aug. 15th**
* ~~Finish defining full API contract by **Monday, Aug. 15th**~~
~~* Implement working registration API by **Sept. 1**~~ (and continuing work afterwards as needed)

**Comment by sohkai** [comment]
@TimDaub should we close this :tada:?

**Comment by TimDaub** [comment]
> @TimDaub should we close this ?

:+1:
