### ISSUE TITLE
Reference implementation of COALA IP

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/org#17]
# Abstract

Implement a reference implementation of COALA IP.
# Motivation

Upgrading SPOOL to use our COALA IP spec allows us to be the forerunning implementation of the spec and set an example for other systems. COALA IP also provides enhancements on top of the current SPOOL architecture:
- Based on LCC RRM for rights management
- Usage of Linked Data
- Compatibility with IPLD
# Goals

Create a Python implementation of COALA IP that runs on top of an immutable ledger, such as IPDB.
# Challenges
- Custom Linked Data schemas will need to be hosted
- Interoperability between Linked Data schemas and IPLD still need to be figured out:
  - How to add IPLD hashing structures to a schema?
- Queryability handling for ledgers
# Tasks

**Deadline: ~~Wednesday, Aug. 17th~~**
- [x] [Define metadata context for COALA IP](https://github.com/ascribe/specs/issues/25)
- [x] [Implement Creation registration in pycoalaip](https://github.com/bigchaindb/pycoalaip/issues/4)
- [x] [Implement Rights registration in pycoalaip](https://github.com/bigchaindb/pycoalaip/issues/14)
- [x] [Implement Rights transfers in pycoalaip](https://github.com/bigchaindb/pycoalaip/issues/15)
- [x] [End-to-end "loan" capability for coalaip-http-api](https://github.com/bigchaindb/coalaip-http-api/issues/6)
- [x] [Put pycoalaip on PyPi](https://github.com/ascribe/specs/issues/27)

**Future**
- [ ] [Host Linked Data context](https://github.com/bigchaindb/pycoalaip/issues/17)
- [x] [Investigate document linking and queryability](https://github.com/ascribe/specs/issues/35)
- [x] ~~[Research and identify potential identity services COALA IP could use](https://github.com/ascribe/specs/issues/28)~~

**Comment by TimDaub** [comment]
> End-to-end "loan" capability for pycoalaip

@sohkai I replaced `pycoalaip` with `coalaip-http-api` here and also updated the ticket's description: https://github.com/bigchaindb/coalaip-http-api/issues/6

**Comment by TimDaub** [comment]
Closing this as it's completed (except for hosting the JSON-LD contexts - which there is a separate ticket for)
