### ISSUE TITLE
COALA IP: End to end implementation of Creation registration

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/org#19]
# Abstract

Create a solid foundation for all the layers of COALA IP for us and DACS to build on. Creation registration is the first step to everything, hence the choice.

# Goals

Implement full Creation registration functionality across the entire stack, culminating in a passing integration test that traverses the following layers:

![Alt text](http://g.gravizo.com/g?
  digraph G {
    aize ="4,4";
    "http-wrapper" [shape=box];
    "http-wrapper" -> pycoalaip;
    pycoalaip -> "bigchaindb-coalaip";
    "bigchaindb-coalaip" ->  "bigchaindb-driver";
    subgraph cluster_bdb {
        "bigchaindb-driver" -> ipdb;
        ipdb [label="IPDB/BigchainDB"
        graph[style=dotted];
    }
  }
)

# Phases

## Phase I
- [x] `pycoalaip` needs its repository, and perhaps renaming
- [x] `bigchaindb-coalaip` needs its repository, and perhaps renaming
- [x] Choose licenses with @gmcmullen help :smile: 

## Phase II
- [x] `pycoalaip` packaging boilerplate to be able to pip install it -- just register on PyPI
- [x] `bigchaindb-coalaip` packaging boilerplate to be able to pip install it - just register on PyPI
- [x] `bigchaindb-driver` is usable/callable for a basic TX

## Phase III
- [x] `pycoalaip` implement `REGISTER` -- upload on PyPI (https://github.com/bigchaindb/pycoalaip/issues/4)
- [x] `bigchaindb-coalaip` supports the above operation (`REGISTER`), in an abstract/generic way -- upload on PyPI
- [x] Create HTTP wrapper for pycoalaip that exposes Creation registration (https://github.com/bigchaindb/coalaip-http-api/issues/1)
- [x] Fix cross project dependencies to their uploaded PyPI versions
- [x] Write documentation on usage for DACS

# Notes
The API test assumes that the underlying dependencies (direct and indirect) work as expected. In other words, `pycoalaip` is assumed to work as expected, just so as the others (`bigchaindb-coalaip`, `bigchaindb-driver`).

## Testing infrastructure
`docker` and `docker-compose` can be used to run a `bigchaindb` node. A `ipdb-regtest` mode should be created soon for testing as well.

**Comment by TimDaub** [comment]
I'm gonna close this ticket, as we're about to merge the last relevant PR for this :tada: 
==> https://github.com/bigchaindb/coalaip-http-api/pull/2
