### ISSUE TITLE
Wrapup DACS integration

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/org#22]
This ticket describes what is needed in order to wrapup the BigchainDB
integration with DACS:
## About this ticket:

The goal of this ticket is to collect all the **tasks** that need to be completed in order to finish DACS's integration with BigchainDB.
So if it turns out that the **tasks** (the sub list items) could be broken down into more fine grained tasks, then please make changes to this ticket.
## Tasks:
- [x] Complete separation of client (transfer is possible)
  - [x] [bigchaindb-common#4](https://github.com/bigchaindb/bigchaindb-common/pull/4): Finalize transaction model > @TimDaub
  - [x] [bigchaindb#586](https://github.com/bigchaindb/bigchaindb/pull/641): Integrate transaction model in BigchainDB > @TimDaub
  - [x] Provide API endpoints for assets > @diminator
  - [x] [bigchaindb#312](https://github.com/bigchaindb/bigchaindb/issues/312): Refactor BigchainDB code into different modules 
    - [x] ~~document multiprocessing @vrde~~
    - [x] [bigchaindb#500](https://github.com/bigchaindb/bigchaindb/issues/500): remove plugin architecture @sbellem 
- [x] [org#17](https://github.com/bigchaindb/org/issues/17) Wrapup implementation of COALA IP
  - [x] ~~[bigchaindb-driver#30](https://github.com/bigchaindb/bigchaindb-driver/issues/30) Revisit transfer's inputs > @sbellem~~ 
  - [x] [pycoalaip-bigchaindb#10](https://github.com/bigchaindb/pycoalaip-bigchaindb/issues/10) Support asset transfers > @sohkai
  - [x] [pycoalaip#14](https://github.com/bigchaindb/pycoalaip/issues/14) Register a COALA IP Right > @Sohkai
  - [x] [pycoalaip#15](https://github.com/bigchaindb/pycoalaip/issues/15) Transfer a COALA IP Right > @Sohkai
  - [x] ~~[pycoalaip#16](https://github.com/bigchaindb/pycoalaip/issues/16) End-to-end "loan" functionality complete > @Sohkai~~
  - [x] [coalaip-http-api#4](https://github.com/bigchaindb/coalaip-http-api/issues/4) Register a COALA IP Right > @TimDaub
  - [x] [coalaip-http-api#5](https://github.com/bigchaindb/coalaip-http-api/issues/5) Transfer a COALA IP Right > @TimDaub
  - [x] [coalaip-http-api#6](https://github.com/bigchaindb/coalaip-http-api/issues/6) End-to-end "loan" functionality complete > @TimDaub
  - [x] ~~[pycoalaip#17](https://github.com/bigchaindb/pycoalaip/issues/17) Complete and host JSON-LD RDF models~~
  - [x] [pycoalaip#18](https://github.com/bigchaindb/pycoalaip/issues/18) Querying capability for "history" of an asset
  - [x] [coalaip-http-api#7](https://github.com/bigchaindb/coalaip-http-api/issues/7) Querying capability for "history" of an asset
  - [x] [bigchaindb#488](https://github.com/bigchaindb/bigchaindb/issues/488) Add support for divisible assets > @r-marques
- [x] [org#13](https://github.com/bigchaindb/org/issues/13) 5 DACS demo artist's images registered on IPDB
  - [x] [org#5](https://github.com/bigchaindb/org/issues/5) Host a test net usable by vetted 3rd parties > @ttmc (maybe split this into tasks if possible)
  - [x] [memetracker#17](https://github.com/ascribe/memetracker/issues/17) Images get registered from us on IPDB using pycoalaip
  - [x] [memetracker#16](https://github.com/ascribe/memetracker/issues/16) Add the registration transaction's id as meta data to the image
  - [x] [memetracker#11](https://github.com/ascribe/memetracker/issues/11) Show transaction id in UI
  - [x] [memetracker#18](https://github.com/ascribe/memetracker/issues/18) Fix false positives on WOTN with UX
  - [x] [memetracker#19](https://github.com/ascribe/memetracker/issues/19) Delete images from WOTN that were not selected by DACS

**Comment by TimDaub** [comment]
> org#5 Host a test net usable by vetted 3rd parties > @ttmc

This is a whole project currently.
If we can split this up into tasks and replace it with them, that'd be better.

**Comment by ttmc** [comment]
@TimDaub Yes, [org#5](https://github.com/bigchaindb/org/issues/5) is a whole project, but it's also basically done. To run a "test net usable by vetted 3rd parties," one can [use the existing AWS deployment scripts](https://bigchaindb.readthedocs.io/en/latest/clusters-feds/aws-testing-cluster.html).

**Comment by trentmc** [comment]
It's not just "a test net" it's "ipdb test net". It would be cool if it's as simple as using existing deployment scripts. Is that really all there is?

**Comment by diminator** [comment]
@TimDaub @trentmc : added the open refactor issues

**Comment by sohkai** [comment]
Depending on the design of https://github.com/bigchaindb/pycoalaip/issues/18, another ticket might be added to https://github.com/bigchaindb/pycoalaip-bigchaindb.

**Comment by sohkai** [comment]
@sbellem and I decided that https://github.com/bigchaindb/bigchaindb-driver/issues/30's scope is somewhat too large for this project, and shouldn't be done before https://github.com/bigchaindb/bigchaindb/pull/590 is merged.

A few changes may be necessary to the driver, such as exposing a way to create transactions; a new task may be replacing https://github.com/bigchaindb/bigchaindb-driver/issues/30 in the context of this project.

**Comment by TimDaub** [comment]
> org#5 Host a test net usable by vetted 3rd parties > @ttmc (maybe split this into tasks if possible)

I marked this as done, as for the scope of DACS there is nothing left to do.

**Comment by TimDaub** [comment]
> memetracker#18 Fix false positives on WOTN with UX

@vrde 

It seems to me that this was done and presented to the project's stakeholders. I'll mark it as done in this ticket.

**Comment by TimDaub** [comment]
> [bigchaindb#501](https://github.com/bigchaindb/bigchaindb/issues/501): group consensus logic @r-marques 

Removed this issue from the scope of this ticket, as with the integration into MongoDB it might become solved/irrelevant.

**Comment by TimDaub** [comment]
There are 9 outstanding PRs on https://github.com/COALAIP/specs/pulls

To close this ticket, their completion (which is mainly dependent on me to review them) will not be tracked as part of this ticket's efforts.

Hence, I'll close this ticket :tada:!
