### ISSUE TITLE
Interledger Roadmap to v1.0

### ISSUE THREAD

**Issue by diminator** [bigchaindb/org#23]
Engagement with ILP allows BDB to partake in the overall ILP network, and provides driver functionality out of the box

See https://docs.google.com/presentation/d/1uguhPmuCUmV7JcJYL5ZNnbjIOqb7ApFOluA1pFhjh1Q/edit#slide=id.g179fd8610f_0_87 as supporting documentation

To get there we'd need to do the following:
- [ ] Keep the python implementation of `py-crypto-conditions` close to [RFC-002](https://interledger.org/five-bells-condition/spec.html) as with the [JS](https://github.com/interledger/five-bells-condition) and [JAVA](https://github.com/interledger/java-crypto-conditions) reference implementation @sohkai 
  - [ ] rename `bigchaindb/cryptoconditions` to `py-crypto-conditions` @sohkai 
  - [ ] (optionally ask to support this under `interledger/py-crypto-conditions` @sohkai 
  - [ ] create extension for bdb in repo `py-bdb-crypto-conditions` @sohkai 
  - [ ] move `TimeoutFulfillment` to `py-bdb-crypto-conditions` [cryptoconditions#29](https://github.com/bigchaindb/cryptoconditions/issues/29) @sohkai 
  - [ ] move `InvertedThresholdSha256Fulfillment` to `py-bdb-crypto-conditions` [cryptoconditions#30](https://github.com/bigchaindb/cryptoconditions/issues/30) @sohkai 
  - [ ] move partial fulfillment issue and PR to `py-bdb-crypto-conditions` [cryptoconditions#24](https://github.com/bigchaindb/cryptoconditions/issues/24) @TimDaub 
- [ ] Provide an ILP API for the bigchaindb web server @sbellem 
  - [ ] finalize the `ilp-web-api` [specification](https://github.com/diminator/rfcs/blob/155f0b42256abaafb5852fc452003536ee259394/0012-ledger-web-api/0012-ledger-web-api.md) and get PR approved @sbellem 
  - [ ] create a new repository for `bdb-ilp-api` @sbellem 
  - [ ] implement endpoints for REST API following the [RFC-0012 spec](https://github.com/diminator/rfcs/blob/155f0b42256abaafb5852fc452003536ee259394/0012-ledger-web-api/0012-ledger-web-api.md) @sbellem @libscott 
  - [ ] update and integrate a websocket server following the [RFC-004 spec](https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#events), see also work done in [bigchaindb-examples](https://github.com/bigchaindb/bigchaindb-examples/blob/master/server/tornado_app.py) @sbellem 
  - [ ] write a request to the ILP community to provide a `js-ilp-plugin-web` @sbellem

**Comment by ttmc** [comment]
Based on the last two offsite meetings (for long-term, high-level planning), the BigchainDB team has no short-, medium- or long-term plans to enhance or increase engagement or integrations with Interledger / ILP.

Note: ILP no longer includes crypto conditions. See section 6 in this blog post: https://medium.com/interledger-blog/simplifying-interledger-the-graveyard-of-possible-protocol-features-b35bf67439be 

Also, almost everyone referenced in this issue is no longer working on BigchainDB.
